### ISSUE TITLE
Clisp binary does not work

### ISSUE THREAD

**Issue by jacqt** [Microsoft/CommandLine-Documentation#15]
After installing clisp with `apt-get install clisp`, running `clisp` results in the following error:

```
/usr/lib/clisp-2.49/base/lisp.run: error while loading shared libraries: libavcall.so.0: cannot enable executable stack as shared object requires: Invalid argument
```

**Comment by hjc4869** [comment]
coreclr dotnet cli shows the same error.

```
Failed to load /usr/share/dotnet/bin/libcoreclr.so, error: /usr/share/dotnet/bin/libcoreclr.so: cannot enable executable stack as shared object requires: Invalid argument
Failed to bind to coreclr
```

**Comment by HotelCalifornia** [comment]
So does trying to compile rakudobrew from source:

    Building NQP ...
/usr/bin/perl Configure.pl --prefix=/root/rakudo-star-2016.01/install --backends=moar --make-install
/root/rakudo-star-2016.01/install/bin/moar: error while loading shared libraries: libmoar.so: cannot enable executable stack as shared object requires: Invalid argument

**Comment by HotelCalifornia** [comment]
This could have something to do with the amount of memory allocated to the WSL/bash-- running `lshw` shows:

    *-memory
          description: System memory
          physical id: 0
          size: 1006MiB

**Comment by bitcrazed** [comment]
We have a fix in the works for the CoreCLR issue; it may also remedy the CLISP issue too.

If not, please open a bug on our [main issues page](https://github.com/microsoft/bashonwindows) as we're trying to wind-down this mistakenly opened issues page.

**Comment by swissarmykirpan** [comment]
@bitcrazed can you reference the ticket representing the fix so we can track it?

**Comment by bitcrazed** [comment]
#302 is tracking an issue with CoreCLR being unable to run due to a dependency on Lttng.We are also tracking issues filed internally and trying our best to get CoreCLR support into our RTM release. No guarantees, but bear with us.

**Comment by brunozorima** [comment]
What is the solution guys??

Thanks

**Comment by sunilmut** [comment]
`clisp` works fine on build 17074. I am not sure exactly which fix fixed it, but, it's working now anyways.

@brunozorima - Not sure which Windows build you are running (you can see using the `ver` command), but, you can try upgrade to Creators Update build and see if that resolves the issue. If not, the next major release should fix it (unless you want to sign-up for Insider builds).

**Comment by maiterth** [comment]
Is there any solution for non up to date systems ("due to company approved updates only")?

**Comment by bitcrazed** [comment]
Hey all. Wow, this is a blast from the past ;)

@maiterth Sorry, no: WSL is not a stand-alone feature - it's highly dependent upon many other areas of the Windows Kernel, including changes that other kernel feature teams have made to accommodate WSL's needs (e.g. networking, filesystem). As such, we VERY strongly recommend all WSL users run the most recent release of Windows 10 in order to ensure that you're running atop the version of WSL with the most features & fixes.

I do encourage you to reach out to your IT team and discuss this with them: We've actually heard from several users who did this and were told "oh, you're a WSL user? Us too!! Yeah, you'll have a much better experience running a more recent version of Win10, we'll get you upgraded ASAP".

YMMV ;)
